CHECK_MARK = "*"
CROSS_MARK = " "
BULLET = ">"
CURSOR = "_"
ACTIVE_DOT = "●"

STARTUP_MESSAGES = [
    "TICK",
    "COPYRIGHT 2024-2025 CACHED INDUSTRIES",
    "LOADER V1.1",
    "EXEC VERSION 41.10",
    "-SERVER 1-"
]

SHUTDOWN_MESSAGES = [
    "SHUTTING DOWN TICK",
    "SAVING SESSION DATA...",
    "CLEARING MEMORY...",
    "GOODBYE."
]
