name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"  # Use latest stable Python for linting
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black ruff mypy isort bandit pylint
          
      - name: Check code formatting with Black
        run: black --check .
        
      - name: Lint with Ruff
        run: ruff check .
        
      - name: Check import sorting with isort
        run: isort --check-only --profile black .
        
      - name: Type check with mypy
        run: mypy . || true
        
      - name: Security check with Bandit
        run: bandit -r . -c pyproject.toml || true
        
      - name: Basic lint with Pylint
        run: pylint --rcfile=pyproject.toml --disable=all --enable=error,warning,refactor --jobs=4 --recursive=y ticked/ || true
